spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: false
  datasource:
      url: jdbc:h2:mem:price-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      platform: h2
      data-username: sa
      data-password:
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  devtools:
    livereload:
      enabled: true
  boot:
    admin:
     client:
        url: http://localhost:9092
        username: admin
        password: admin
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}${random.uuid}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"